Add support for Rewards Twitter publishers
brave/brave-site-specific-scripts pull request #16
Opened 2020-09-21 16:29 UTC by emerick

Associated brave-core PR: https://github.com/brave/brave-core/pull/5440

Adds support for Twitter-based publisher tips via a Greaselion script. The script reacts to URL navigations and state changes by sending the associated publisher info to the Rewards extension, allowing tips to be supported via the Rewards panel and an injected inline tip button in the user's Twitter feed.

2020-09-25 14:44 UTC, pilgrim-brave approved these changes

2020-09-25 15:12 UTC, petemill submitted a review, later dismissed
A minor change and a bigger question. Be good to avoid ports if we can unless we're doing some communication that's initiated from the rewards extension background page?

2020-09-25 15:12 UTC, petemill commented on scripts/brave_rewards/publisher/twitter/twitter.ts
> +    port.onMessage.addListener(function (msg) {
Is there a reason to use port.postMessage here instead of runtime.sendMessage?
Disadvantages that I know of for using long lived ports instead of individual messages:
- ports don't allow callback within the message handler, complicating code flow as you lose state
- ports keep the extension background script alive, preventing it from going to sleep / ending

2020-09-25 15:21 UTC, emerick commented on scripts/brave_rewards/publisher/twitter/twitter.ts
> +    }
Good catch, fixed.

2020-09-25 15:30 UTC, emerick commented on scripts/brave_rewards/publisher/twitter/twitter.ts
> +    port.onMessage.addListener(function (msg) {
It seems like Greaselion is geared towards one-way communication originating from the content script. In this integration and the YouTube one, I had the need to send a message from the Rewards extension to the content script. This is primarily occurring to relay results from `chrome` APIs that can't be called from an extension, such as `chrome.webRequest.onSendHeaders`.

The only reliable way I found to communicate in that direction was to open a long-lived port from the Greaselion content script. Other approaches (such as reading the Greaselion extension ID from the message sender object and using that to call `runtime.sendMessage`) didn't work as they seemed to necessitate access to the Greaselion extension's background page.

Definitely open to other ideas, but it was the best approach I found so far.

2020-09-25 16:03 UTC, petemill commented on scripts/brave_rewards/publisher/twitter/twitter.ts
> +    port.onMessage.addListener(function (msg) {
Ok yeah if we're still handling those events then the background page will be persistent anyway. I was of the impression from @NejcZdovc that we were able to not depend on these APIs anymore but I was mistaken. We should aim to have a TabHelper in c++ listen to these APIs and filter the headers we need before sending them to us somehow, still probably via the extension. Maybe at that point we could "ask" the extension for the headers each time we need them instead of being pushed them.

2020-09-25 16:39 UTC, zenparsing commented on scripts/brave_rewards/publisher/twitter/twitter.ts
> +          id: details.user.id_str,
It seems like `getTweetDetails` can resolve with undefined, but we're assuming an object here. We should either reject instead of resolving with undefined, or have callers check for that condition.

2020-09-25 16:39 UTC, zenparsing commented on scripts/brave_rewards/publisher/common/utils.ts
> +export const areObjectsEqual = (firstObj: {}, secondObj: {}) => {
Just a thought: since this doesn't do a deep comparison (but only a first-level comparison of values), I'd worry a bit about it being misused. If we want to keep it in "common/utils", then perhaps put "shallow" in the name?

2020-09-25 16:39 UTC, zenparsing commented on scripts/brave_rewards/publisher/twitter/twitter.ts
> +      publisherName,
It seems like we're sending "screenName" and not a publisher name (which I *think* can be different).

More generally, is the idea to normalize the data that is provided when sending "TipUser" (and then on to the tip dialog)? That seems like a good idea, but currently the data is different for the different media types. Are we sure that this same data structure will work for other media types (like Reddit, which has a `mediaMetaData.postRelDate` instead of a timestamp, for instance)?

For reference, here are the current MediaMetaData types that the tip dialog uses:

```ts
type TwitterMediaData = {
  mediaType: 'twitter'
  twitterName: string
  screenName: string
  userId: string
  tweetId: string
  tweetTimestamp: number
  tweetText: string
}

type RedditMediaData = {
  mediaType: 'reddit'
  userName: string
  postText: string
  postRelDate: string
}

type GithubMediaData = {
  mediaType: 'github'
  userName: string
}
```

2020-09-25 16:47 UTC, emerick commented on scripts/brave_rewards/publisher/twitter/twitter.ts
> +    port.onMessage.addListener(function (msg) {
I like that the sound of that. My preference would be to do it as a follow-up task (if we're all on board with the idea in general), so we can keep moving on Rewards Everywhere.

2020-09-25 17:26 UTC, emerick commented on scripts/brave_rewards/publisher/twitter/utils.ts
> +  for (const strPath of paths) {
Ah that's great, didn't know about that. Fixed.

2020-09-25 17:26 UTC, emerick commented on scripts/brave_rewards/publisher/twitter/utils.ts
> +  for (const strPath of patterns) {
Yup, fixed.

2020-09-25 17:26 UTC, emerick commented on scripts/brave_rewards/publisher/twitter/utils.ts
> +export const getUserIdFromUrl = (url: URL) => {
Removed.

2020-09-25 17:26 UTC, emerick commented on scripts/brave_rewards/publisher/twitter/utils.ts
> +  if (components.length === 1 && components[0] === document.title) {
Fixed.

2020-09-25 17:27 UTC, emerick commented on scripts/brave_rewards/publisher/twitter/utils.ts
> +export const getUserNameFromUrl = (url: URL) => {
Good point, fixed.

2020-09-25 17:27 UTC, emerick commented on scripts/brave_rewards/publisher/twitter/twitter.ts
> +  if (!url) {
Fixed.

2020-09-25 17:28 UTC, emerick commented on scripts/brave_rewards/publisher/twitter/auth.ts
> +        authHeaders = {}
I think the idea is to just discard everything we have when a new `Cookie` header arrives.

2020-09-25 17:29 UTC, emerick commented on scripts/brave_rewards/publisher/twitter/auth.ts
> +export const processRequestHeaders = (requestHeaders: any[], callback: (authHeaders: {}) => void) => {
Ah good point, the callback was a holdover from a different approach I was trying. Removed.

2020-09-25 17:29 UTC, emerick commented on scripts/brave_rewards/publisher/twitter/auth.ts
> +// localStorage.removeItem('twitterAuthHeaders')
Yes, removed.

2020-09-25 17:29 UTC, emerick commented on scripts/brave_rewards/publisher/twitter/twitter.ts
> +  return new Promise((resolve, reject) => {
Good tip, fixed!

2020-09-25 17:29 UTC, emerick commented on scripts/brave_rewards/publisher/twitter/twitter.ts
> +          id: details.user.id_str,
Fixed.

2020-09-25 17:29 UTC, emerick commented on scripts/brave_rewards/publisher/common/utils.ts
> +export const areObjectsEqual = (firstObj: {}, secondObj: {}) => {
Yes, makes sense. Renamed.

2020-09-25 17:33 UTC, emerick commented on scripts/brave_rewards/publisher/twitter/twitter.ts
> +      publisherName,
You're right `screenName` is different from the publisher name. I was surprised to notice that too, but it seems that we show the screen name in Twitter on `master` so I was just going for parity there.

Regarding the metadata, yes my plan there was to normalize the data using the same structure for all media types. Regarding `postRelDate` my hope was to convert that into a compatible timestamp format before sending it to C++. Maybe that's overly optimistic, though...

2020-09-25 17:43 UTC, emerick commented on scripts/brave_rewards/publisher/twitter/auth.ts
> +    if (header.name === 'Cookie') {
I think it's OK because it's what we've been using on `master` for a while now, I basically just ported it over to Greaselion.

2020-09-28 09:50 UTC, NejcZdovc commented on scripts/brave_rewards/publisher/twitter/auth.ts
> +  const match = cookiesString.match(authTokenCookieRegex)
check that `cookiesString` is defined

2020-09-28 09:51 UTC, NejcZdovc commented on scripts/brave_rewards/publisher/twitter/twitter.ts
> +// FIXME: This needs to use localized strings
please log an issue for it and reference it here

2020-09-28 09:55 UTC, NejcZdovc commented on scripts/brave_rewards/publisher/twitter/twitter.ts
> +  style.innerHTML = '.ProfileTweet-actionButton :hover { color: #FB542B }'
we should avoid innerHTML

```
const style = document.createElement('style')
const css = '.ProfileTweet-actionButton :hover { color: #FB542B }'
style.appendChild(document.createTextNode(css))
braveTipButton.appendChild(style)
```

2020-09-28 09:57 UTC, NejcZdovc commented on scripts/brave_rewards/publisher/twitter/twitter.ts
> +const handleOnUpdatedTab = (mediaType: string, tabId: number, changeInfo: any, tab: chrome.tabs.Tab) => {
do we need to have all this args coming in while we just need `changeInfo`?

2020-09-28 09:58 UTC, NejcZdovc commented on scripts/brave_rewards/publisher/twitter/utils.ts
> +  return `${types.mediaType}#channel:${key}`
check if key is empty and return empty in this case

2020-09-28 09:58 UTC, NejcZdovc commented on scripts/brave_rewards/publisher/twitter/utils.ts
> +  return `${types.mediaType}_${mediaId}`
check if key is empty and return empty in this case

2020-09-28 09:59 UTC, NejcZdovc commented on scripts/brave_rewards/publisher/twitter/utils.ts
> +  const searchParams = new URLSearchParams(url.search)
check if url is not defined

2020-09-28 15:40 UTC, emerick commented on scripts/brave_rewards/publisher/twitter/auth.ts
> +  const match = cookiesString.match(authTokenCookieRegex)
Fixed.

2020-09-28 15:40 UTC, emerick commented on scripts/brave_rewards/publisher/twitter/twitter.ts
> +  style.innerHTML = '.ProfileTweet-actionButton :hover { color: #FB542B }'
Good point, fixed.

2020-09-28 15:40 UTC, emerick commented on scripts/brave_rewards/publisher/twitter/twitter.ts
> +const handleOnUpdatedTab = (mediaType: string, tabId: number, changeInfo: any, tab: chrome.tabs.Tab) => {
Fixed.

2020-09-28 15:40 UTC, emerick commented on scripts/brave_rewards/publisher/twitter/utils.ts
> +  return `${types.mediaType}#channel:${key}`
Fixed.

2020-09-28 15:40 UTC, emerick commented on scripts/brave_rewards/publisher/twitter/utils.ts
> +  return `${types.mediaType}_${mediaId}`
Fixed.

2020-09-28 15:40 UTC, emerick commented on scripts/brave_rewards/publisher/twitter/utils.ts
> +  const searchParams = new URLSearchParams(url.search)
I was doing that originally, but @zenparsing mentioned that it's impossible to construct a null URL.

2020-09-28 15:49 UTC, zenparsing commented on scripts/brave_rewards/publisher/twitter/twitter.ts
> +    return Promise.reject(null)
A general guideline is to always reject with an Error instance.

2020-09-28 15:49 UTC, zenparsing commented on scripts/brave_rewards/publisher/twitter/twitter.ts
> +    return Promise.reject('Invalid parameters')
We should reject with an error: `new Error('Invalid parameters')`. 

Since this is an async function, you can also just do `throw new Error('Invalid parameters')`.

2020-09-28 15:49 UTC, zenparsing commented on scripts/brave_rewards/publisher/twitter/twitter.ts
> +      const userId = userDetails.id_str
Looks like `userDetails` can be `undefined` here, as there's an early return in `getUserDetails`.

2020-09-28 15:59 UTC, zenparsing commented on scripts/brave_rewards/publisher/twitter/twitter.ts
> +    port.onMessage.addListener(function (msg) {
It looks like this listener is attached for each API request. Is this listener removed at any point?

2020-09-28 17:50 UTC, emerick commented on scripts/brave_rewards/publisher/twitter/twitter.ts
> +    return Promise.reject(null)
Yup, makes sense. Fixed.

2020-09-28 17:50 UTC, emerick commented on scripts/brave_rewards/publisher/twitter/twitter.ts
> +    return Promise.reject('Invalid parameters')
Thanks, fixed.

2020-09-28 17:50 UTC, emerick commented on scripts/brave_rewards/publisher/twitter/twitter.ts
> +      const userId = userDetails.id_str
Fixed.

2020-09-28 17:51 UTC, emerick commented on scripts/brave_rewards/publisher/twitter/twitter.ts
> +    port.onMessage.addListener(function (msg) {
Great catch, fixed.

2020-09-28 20:40 UTC, zenparsing commented on scripts/brave_rewards/publisher/twitter/twitter.ts
> +        port.onMessage.removeListener(onMessageListener)
It seems like the listener should be removed for any of the code paths where the promise is resolved or rejected (after it's fulfilled there's no way for that data to flow to the caller anyway).

2020-09-28 21:05 UTC, emerick commented on scripts/brave_rewards/publisher/twitter/twitter.ts
> +        port.onMessage.removeListener(onMessageListener)
Good point, fixed.

2020-09-28 23:34 UTC, emerick commented on scripts/brave_rewards/publisher/twitter/twitter.ts
> +// FIXME: This needs to use localized strings
Created https://github.com/brave/brave-browser/issues/11890 to track this.

2020-09-29 18:33 UTC, zenparsing submitted a review, later dismissed

2020-09-30 15:17 UTC, zenparsing submitted a review, later dismissed

2020-10-02 05:02 UTC, NejcZdovc requested changes
getting build errors on the latest code

```
ERROR in /Users/nz/Work/Brave/brave-site-specific-scripts/scripts/brave_rewards/publisher/twitter/twitter.ts
[tsl] ERROR in /Users/nz/Work/Brave/brave-site-specific-scripts/scripts/brave_rewards/publisher/twitter/twitter.ts(503,13)
      TS6133: 'profileUrl' is declared but its value is never read.
```

2020-10-02 12:56 UTC, emerick commented
@NejcZdovc Fixed compilation error, sorry I had a local `console.log` that used the variable and masked it.

2020-10-05 18:02 UTC, NejcZdovc approved these changes

2020-10-05 19:56 UTC, zenparsing approved these changes

2020-10-05 21:46 UTC, merged

2020-10-07 05:45 UTC, petemill reviewed
This works as a port to greaselion. 👍 
I think it would be great for future implementations to not put everything in a single 600 LOC module and split out some of the functions, especially the ones that looks standalone. It would be great to have a main module for twitter that is small and only contains the logic of the lifecycle of tip and media metadata, and break out in to other modules for each of those details. Might be easier to follow and maintain.