Add support for Rewards Reddit publishers
brave/brave-site-specific-scripts pull request #21
Opened 2020-10-09 11:06 UTC by emerick

Associated brave-core PR: 

Adds support for Reddit-based publisher tips via a Greaselion script. The script reacts to URL navigations and state changes by sending the associated publisher info to the Rewards extension, allowing tips to be supported via the Rewards panel and an injected inline tip button in the user's Github pages.

2020-10-13 18:35 UTC, emerick commented on scripts/brave_rewards/publisher/reddit/reddit.ts
> +    return
Good point, fixed.

2020-10-13 18:36 UTC, emerick commented on scripts/brave_rewards/publisher/reddit/tipping.ts
> +    const divPostTextElement = (authorAnchorElement[0] as HTMLAnchorElement)
Thanks, I cleaned up a bunch of those but didn't catch them all apparently!

2020-10-13 18:36 UTC, emerick commented on scripts/brave_rewards/publisher/reddit/tipping.ts
> +      if (postTextElements[0].innerText) {
Fixed.

2020-10-13 18:36 UTC, emerick commented on scripts/brave_rewards/publisher/reddit/tipping.ts
> +            postRelativeDate = timeSpan[0].textContent || ''
Fixed.

2020-10-13 18:36 UTC, emerick commented on scripts/brave_rewards/publisher/reddit/tipping.ts
> +  style.appendChild(document.createTextNode(css))
Fixed.

2020-10-13 18:36 UTC, emerick commented on scripts/brave_rewards/publisher/reddit/tipping.ts
> +  for (let ix = 0; ix < postElements.length; ++ix) {
Fixed.

2020-10-13 18:36 UTC, emerick commented on scripts/brave_rewards/publisher/reddit/tipping.ts
> +    if (!actions || actions.length > 0 || inEditModeElements) {
Fixed.

2020-10-13 18:36 UTC, emerick commented on scripts/brave_rewards/publisher/reddit/tipping.ts
> +      configureForMoreInfoElement(postElements[ix], lastElement, isForPosts, !!isUsersPost)
Good point, fixed.

2020-10-13 18:36 UTC, emerick commented on scripts/brave_rewards/publisher/reddit/tipping.ts
> +  if (!elements) {
Fixed.

2020-10-13 18:37 UTC, emerick commented on scripts/brave_rewards/publisher/reddit/tipping.ts
> +  for (let ix = 0; ix < elements.length; ++ix) {
Fixed.

2020-10-13 18:37 UTC, emerick commented on scripts/brave_rewards/publisher/reddit/tipping.ts
> +    if (!actions || actions.length > 0) {
Fixed.

2020-10-13 18:37 UTC, emerick commented on scripts/brave_rewards/publisher/reddit/tipping.ts
> +    if (!ulElement || ulElement.length === 0) {
Fixed.

2020-10-13 18:37 UTC, emerick commented on scripts/brave_rewards/publisher/reddit/tipping.ts
> +  if (!port || !mediaMetaData) {
Fixed.

2020-10-13 18:51 UTC, emerick commented on scripts/brave_rewards/publisher/reddit/tipping.ts
> +    configureForPosts(false, false)
Good idea, fixed.

2020-10-13 18:52 UTC, emerick commented on scripts/brave_rewards/publisher/reddit/tipping.ts
> +  return document.evaluate(".//button[text()='Save']", commentElement, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue as HTMLElement
Nothing else I tried there worked, but let me take a look again. I'm not crazy about the XPath either.

2020-10-13 21:33 UTC, emerick commented on scripts/brave_rewards/publisher/reddit/tipping.ts
> +  return document.evaluate(".//button[text()='Save']", commentElement, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue as HTMLElement
Hmm, I'm not sure that this is doable without XPath unfortunately. All of the CSS class names are dynamically generated so it's impossible to use those for anything. The `Share` button does have a `data-click-id` attribute, but the other buttons don't (some buttons have other `data-*` attributes, but they don't represent IDs and probably can't be relied on for identification purposes).

2020-10-13 21:33 UTC, emerick commented on scripts/brave_rewards/publisher/reddit/tipping.ts
> +  const saveElement = document.evaluate(".//span[text()='save']", element, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue as HTMLElement
It doesn't seem so, unfortunately; see above.

2020-10-13 21:33 UTC, emerick commented on scripts/brave_rewards/publisher/reddit/tipping.ts
> +  return document.evaluate(".//button[text()='edit']", commentElement, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue
It doesn't seem so, unfortunately; see above.

2020-10-13 21:34 UTC, emerick commented on scripts/brave_rewards/publisher/reddit/tipping.ts
> +  return document.evaluate(".//button[text()='edit']", commentElement, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue
Fixed.

2020-10-15 09:10 UTC, NejcZdovc requested changes
1) homepage has empty panel https://www.reddit.com/
![image](https://user-images.githubusercontent.com/9574457/96100999-4564f800-0ed5-11eb-91d4-4ac9c535184b.png)

2) inline tip doesn't work on replays https://www.reddit.com/r/MechanicalKeyboards/comments/jb48ur/gmk_noire_first_week_giveaway/
![image](https://user-images.githubusercontent.com/9574457/96101351-a7bdf880-0ed5-11eb-8eb3-e0dbc20a5296.png)

3) user not shown in the panel
https://www.reddit.com/user/AutoModerator/posts
https://www.reddit.com/user/AutoModerator/comments/
![image](https://user-images.githubusercontent.com/9574457/96101814-24e96d80-0ed6-11eb-827a-e98a24f0222a.png)

4) Q: If you are on post can we if we open panel show publisher that posted this
In https://www.reddit.com/r/MechanicalKeyboards/comments/jb48ur/gmk_noire_first_week_giveaway/ case that would be `u/shmarcia`

2020-10-15 13:53 UTC, emerick commented
@NejcZdovc I'm not able to repro #1 or #3. Sometimes I have to wait quite a bit for the panel to populate on reddit (> 5 seconds sometimes), I think the site is a bit slow for some reason. Can you check if that's what's happening? If not, I can investigate, but both work for me on a clean profile.

For #2, we don't show the Tip icon on replies on new Reddit, because there's no longer a toolbar for replies. We do still show the Tip icon on old Reddit, because the toolbar is there. Let me know if I'm misunderstanding, though.

#4 - Seems doable, will work on that today.

2020-10-15 18:57 UTC, emerick commented
Item `#4` addressed now, other feedback was responded to.

2020-10-16 14:04 UTC, NejcZdovc approved these changes

2020-10-16 14:33 UTC, zenparsing approved these changes

2020-10-16 14:54 UTC, merged