Add support for Rewards Vimeo publishers
brave/brave-site-specific-scripts pull request #24
Opened 2020-10-26 18:10 UTC by emerick

Associated brave-core PR: https://github.com/brave/brave-core/pull/6955

Adds support for Vimeo-based publisher tips via a Greaselion script. The script reacts to URL navigations and state changes by sending the associated publisher info to the Rewards extension, allowing tips to be supported via the Rewards panel.

2020-10-26 18:12 UTC, emerick commented
Note: This looks a bit complicated at the moment, because it's based on the PR to split out the Rewards scripts into panel/tipping components (https://github.com/brave/brave-site-specific-scripts/pull/22). Once that PR is merged, I'll rebase and this will just be Vimeo-specific as expected.

2020-10-28 06:42 UTC, NejcZdovc commented on Greaselion.json
> +      "rewards-enabled": true
you don't need to add this anymore as we limited to 1.18 where this flag is legacy

2020-10-28 06:42 UTC, NejcZdovc commented on Greaselion.json
> +      "scripts/brave_rewards/publisher/vimeo/vimeo.bundle.js"
let's name this one as Base as well, so that we follow the same naming convention

2020-10-28 07:25 UTC, NejcZdovc requested changes
1) video switching not updating the publisher
- go to https://vimeo.com/465498401 for example
- open panel and see that publisher is displayed correctly
- then click on a video that is suggested at the bottom
- open panel and see that panel is empty

2) channel staff video doesn't work
- go to https://vimeo.com/channels/staffpicks
- click on any video 
- you are redirect to a page like this https://vimeo.com/channels/staffpicks/465498401
- open a panel and you will see vimeo.com instead of publisher info

2020-10-28 16:33 UTC, NejcZdovc commented on Greaselion.json
> +    "minimum_brave_version": "1.17"
left over from a rebase probably

2020-10-28 16:57 UTC, emerick commented on Greaselion.json
> +    "minimum_brave_version": "1.17"
Yes, thank you.

2020-10-28 18:42 UTC, emerick commented on Greaselion.json
> +      "scripts/brave_rewards/publisher/vimeo/vimeo.bundle.js"
Makes sense, fixed.

2020-10-28 18:43 UTC, emerick commented
@NejcZdovc All review feedback addressed, ready for review again.

2020-10-29 11:02 UTC, NejcZdovc approved these changes

2020-10-30 16:44 UTC, zenparsing approved these changes

2020-10-30 16:47 UTC, merged