Rewards auto contribution support
brave/brave-site-specific-scripts pull request #28
Opened 2020-11-06 23:39 UTC by emerick

Add auto-contribution support for Rewards media publishers.

2020-11-06 23:42 UTC, emerick commented
Reviewers: Please note that this PR is based off the `rewards-greaselion-brave-extension` branch, so it's probably simplest to review by commit and simply ignore that particular commit.

2020-11-13 17:54 UTC, marshall approved these changes
looks great. there is a pretty big chunk of common logic between all of the auto contribution scripts you might consider refactoring, but I don't think it needs to hold up this PR.

2020-11-13 17:54 UTC, marshall commented on scripts/brave_rewards/publisher/common/mediaDuration.ts
> +  firstVisit = enabled
should `firstVisit` be also persisted for each site? I may not fully understand it's purpose, but I assume the flag will get reset whenever Brave is restarted, since it's only in memory.

2020-11-13 17:54 UTC, marshall commented on scripts/brave_rewards/publisher/reddit/redditAutoContribution.ts
> +      } else {
this code block (and lines 38-49) seem to be pretty common between scripts. since they're pretty crucial to counting page activity, do you think it makes sense to factor out the code and put it in `common`?

2020-11-13 18:26 UTC, emerick commented on scripts/brave_rewards/publisher/common/mediaDuration.ts
> +  firstVisit = enabled
It's only relevant for the length of the browser session, but you just made me realize that it's not going to work as expected now that I made this common code. Thanks for bringing it up, will fix.

2020-11-13 20:17 UTC, emerick commented on scripts/brave_rewards/publisher/reddit/redditAutoContribution.ts
> +      } else {
Yes, it's been bugging me too. Let me create an issue to refactor this, because I want to do it for all of the scripts (base, publisherInfo, and autoContribution) in the various Rewards media publishers but I think that will get a bit big for this PR.

2020-11-13 20:20 UTC, emerick commented on scripts/brave_rewards/publisher/reddit/redditAutoContribution.ts
> +      } else {
https://github.com/brave/brave-browser/issues/12698

2020-11-17 20:44 UTC, zenparsing reviewed
General question: is media duration tracked appropriately for sites that use the history API? I didn't see "updatedTab" listeners in the new code.

2020-11-17 20:44 UTC, zenparsing commented on scripts/brave_rewards/publisher/vimeo/publisherInfo.ts
> +export const get = async () => {
I see you're gravitating toward short exported names. Nothing wrong with that, although from a practical standpoint it means that importers need to use `import * as` namespace imports instead of pulling in the names that they need.

2020-11-17 20:44 UTC, zenparsing commented on scripts/brave_rewards/publisher/youtube/mediaDuration.ts
> +export const sendMetadataFromUrl = (url: URL) => {
Is "from" intentional? Should it be `sendMetadataForUrl`?

2020-11-17 20:44 UTC, zenparsing commented on scripts/brave_rewards/publisher/common/utils.ts
> +  if (mediaId.startsWith(mediaType)) {
Seems like this could have surprising results for other publisher types, e.g. `twitter` is a valid media ID for the `twitter` media type. Can this special-case logic be moved into the vimeo modules somehow?

2020-11-18 16:03 UTC, emerick commented on scripts/brave_rewards/publisher/vimeo/publisherInfo.ts
> +export const get = async () => {
Yeah, that's a good point. I made that change because `publisherInfo.getPublisherInfo` seemed excessive, maybe I got too carried away. It seems like either choice will be a little problematic. I think I'll keep it as-is for now, but will give it some more thought for the future.

2020-11-18 16:06 UTC, emerick commented on scripts/brave_rewards/publisher/youtube/mediaDuration.ts
> +export const sendMetadataFromUrl = (url: URL) => {
Intentional, but maybe not obvious. I was trying to signify that the metadata is coming from the URL (i.e., we parse it out of the URL).

2020-11-18 16:08 UTC, emerick commented on scripts/brave_rewards/publisher/common/utils.ts
> +  if (mediaId.startsWith(mediaType)) {
Yeah, I'll do that. I'm not even sure that this code is strictly necessary, it just seemed weird to have a media ID of `vimeo_vimeo_12345`.

2020-11-19 17:55 UTC, emerick commented on scripts/brave_rewards/publisher/common/utils.ts
> +  if (mediaId.startsWith(mediaType)) {
This turned out to be a bug (I was passing the media key instead of the raw media ID). Fixed now, thanks for mentioning it.

2020-11-19 21:51 UTC, emerick commented
@zenparsing Addressed the issue you mentioned about using the History API. Should be ready for review again, thanks.

2020-11-23 21:26 UTC, marshall requested changes
overall looks great. I left a few nits but they aren't blockers IMO.

I also pulled this down to test locally and ran into a few minor issues:

* The favicon for github profiles seems to be blank (I tested with my profile by visiting it directly)
* Visiting a youtube channel page seems to count towards AC for youtube.com, instead of a specific profile, and I couldn't get videos to count towards either youtube.com or a specific profile. (The channel I tested with was shared privately)

I think once these are addressed this is good to land. Also it looks like this needs a fresh rebase

2020-11-24 14:53 UTC, emerick commented on scripts/brave_rewards/publisher/common/mediaDuration.ts
> +    mediaType: mediaType,
Fixed.

2020-11-24 15:01 UTC, emerick commented on scripts/brave_rewards/publisher/common/mediaDuration.ts
> +export const sendMetadata = (mediaType: string, mediaId: string, duration: number, firstVisit: boolean) => {
Fixed. Yes, makes sense - I'll enter an issue for that.

2020-11-24 15:06 UTC, emerick commented on scripts/brave_rewards/publisher/common/mediaDuration.ts
> +export const sendMetadata = (mediaType: string, mediaId: string, duration: number, firstVisit: boolean) => {
https://github.com/brave/brave-browser/issues/12874

2020-11-24 20:56 UTC, emerick commented
@marshall Addressed all feedback, though I haven't been able to repro the missing Github favicon. Maybe try with a clean profile? The Youtube issue was an actual bug; we needed to use the YouTube channel ID as the media ID when there's no media key.

2020-11-24 21:54 UTC, marshall reviewed
@emerick looks like there is some async code not using await.. let me know if they're expected or not, and I can test once it's addressed

2020-11-24 21:54 UTC, marshall commented on scripts/brave_rewards/publisher/youtube/publisherInfo.ts
> +      return scrapePublisherInfoFromPage(url)
should this be `return await scrapePublisherInfoFromPage(url)` since the funciton is async ?

2020-11-24 21:54 UTC, marshall commented on scripts/brave_rewards/publisher/youtube/publisherInfo.ts
> +    return getPublisherInfoForUser()
shouldn't these also be be `await`ed?

2020-11-24 21:58 UTC, zenparsing commented on scripts/brave_rewards/publisher/youtube/publisherInfo.ts
> +      return scrapePublisherInfoFromPage(url)
The value returned from an async function is implicitly awaited (technically, the promise corresponding to the async function invocation is resolved with the return value, and resolution will implicitly unwrap promises).

2020-11-24 22:53 UTC, emerick commented on scripts/brave_rewards/publisher/youtube/publisherInfo.ts
> +      return scrapePublisherInfoFromPage(url)
Yeah and actually tslint spits out the following if you attempt it:

```
C:/work/brave-site-specific-scripts/scripts/brave_rewards/publisher/youtube/publisherInfo.ts:98:14
ERROR: 98:14  no-return-await  Unnecessary 'await'.
```

2020-11-24 22:54 UTC, emerick commented on scripts/brave_rewards/publisher/youtube/publisherInfo.ts
> +    return getPublisherInfoForUser()
Our current tslint settings complain about it being "unnecessary" (see above).

2020-11-24 23:30 UTC, marshall commented on scripts/brave_rewards/publisher/youtube/publisherInfo.ts
> +    return getPublisherInfoForUser()
cool thanks for clarifying!

2020-11-24 23:30 UTC, marshall commented on scripts/brave_rewards/publisher/youtube/publisherInfo.ts
> +      return scrapePublisherInfoFromPage(url)
awesome, I wasn't aware of this behavior. thanks for clarification!

2020-11-25 18:46 UTC, marshall approved these changes

2020-11-25 18:56 UTC, merged

2020-11-25 18:56 UTC, emerick commented
This fix will be in Greaselion `1.0.39`.