first ads conversion
brave/brave-site-specific-scripts pull request #46
Opened 2021-02-04 16:34 UTC by amirsaber

2021-02-05 18:54 UTC, amirsaber commented
Check for enabled ads is missing

2021-03-18 16:29 UTC, emerick commented on Greaselion.json
> +      "https://*yubico.com*/checkout/confirmation*"
The stars in the host portion of this url seem problematic. Wouldn't that end up running this script on potentially unrelated sites?

2021-03-18 16:29 UTC, emerick commented on scripts/brave_rewards/ads/conversions/yubico.ts
> +    orderId = el[0].firstChild.firstChild.textContent!.replace('Order Number: ', '')
Is the `!` a typo?

2021-03-18 16:29 UTC, emerick commented on scripts/brave_rewards/ads/conversions/yubico.ts
> +    document.getElementsByTagName('head')[0].appendChild(link)
Probably would be good to do some minimal null checks here.

2021-03-22 16:32 UTC, amirsaber commented on scripts/brave_rewards/ads/conversions/yubico.ts
> +    orderId = el[0].firstChild.firstChild.textContent!.replace('Order Number: ', '')
no it's not, it's a Non-null assertion operator

2021-03-22 16:33 UTC, amirsaber commented on scripts/brave_rewards/ads/conversions/yubico.ts
> +    document.getElementsByTagName('head')[0].appendChild(link)
what line could possibly go null?

2021-03-22 16:34 UTC, emerick commented on scripts/brave_rewards/ads/conversions/yubico.ts
> +    orderId = el[0].firstChild.firstChild.textContent!.replace('Order Number: ', '')
Didn't realize that, nice!

2021-03-22 16:36 UTC, emerick commented on scripts/brave_rewards/ads/conversions/yubico.ts
> +    document.getElementsByTagName('head')[0].appendChild(link)
Is `getElementsByTagName('head')` guaranteed to have an element? I think that's the only one I was concerned about, but maybe it's fine.

2021-03-22 16:38 UTC, amirsaber commented on Greaselion.json
> +      "https://*yubico.com*/checkout/confirmation*"
pushed a change to target domain and subdomains explicitly

2021-03-22 16:43 UTC, emerick commented on Greaselion.json
> +      "https://*yubico.com*/checkout/confirmation*"
Is the `.com*` intentional? It doesn't seem like you need a `*` there, but could be I just don't understand the goal.

2021-03-22 17:09 UTC, diracdeltas commented on Greaselion.json
> +      "ads-enabled": true
@emerick did we ever add the feature to disable greaselion scripts in incognito by default?

2021-03-22 17:12 UTC, diracdeltas commented on Greaselion.json
> +      "https://yubico.com*/checkout/confirmation*"
what's the code that parses these match patterns? would these match `https://yubico.com.example.com` for instance?

2021-03-22 17:14 UTC, diracdeltas commented on scripts/brave_rewards/ads/conversions/yubico.ts
> +    orderId = el[0].firstChild.firstChild.textContent!.replace('Order Number: ', '')
will this work for non-English versions of the page? (assuming they have localization)

2021-03-22 17:15 UTC, diracdeltas commented on webpack.config.js
> +      ['scripts/brave_rewards/ads/conversions/yubico']: './scripts/brave_rewards/ads/conversions/yubico',
should have a wiki page to document why this script is injected. we already have users complaining that the greaselion injected scripts are not transparent enough and can't be disabled.

2021-03-22 17:30 UTC, emerick commented on Greaselion.json
> +      "ads-enabled": true
It hasn't been implemented yet (https://github.com/brave/brave-browser/issues/11409), I'll bring it up at our triage meeting this week!

2021-03-22 18:17 UTC, orspetol requested changes

2021-03-22 18:20 UTC, amirsaber commented on webpack.config.js
> +      ['scripts/brave_rewards/ads/conversions/yubico']: './scripts/brave_rewards/ads/conversions/yubico',
I have a wiki update page written down in the spec, awaiting for the final approval and copy edits on it

2021-03-22 18:27 UTC, amirsaber commented on scripts/brave_rewards/ads/conversions/yubico.ts
> +  if (orderId !== '') {
added substr call on orderId in next line

2021-03-22 18:27 UTC, diracdeltas requested changes
We have an ongoing relationship with Yubico, so let's first ask them if they can make this change without Brave having to inject scripts.

2021-03-22 18:31 UTC, amirsaber commented on Greaselion.json
> +      "https://*yubico.com*/checkout/confirmation*"
```
      "https://*.yubico.com/*/checkout/confirmation*",
      "https://yubico.com/*/checkout/confirmation*"
```
 moved the asterisk to after domain separation from address

2021-03-22 18:34 UTC, amirsaber commented on Greaselion.json
> +      "https://yubico.com*/checkout/confirmation*"
also mentioned by @emerick in above comments, moved asterisk to after `/`

2021-03-22 19:59 UTC, diracdeltas commented on Greaselion.json
> +      "ads-enabled": true
@emerick will a script with `ads-enabled` true get injected into incognito/tor windows?

2021-03-22 20:02 UTC, emerick commented on Greaselion.json
> +      "ads-enabled": true
I believe so, as it seems that supporting incognito mode is the default for extensions.

2021-03-22 20:25 UTC, emerick commented on Greaselion.json
> +      "ads-enabled": true
Actually, I didn't realize that we've recently made the following change to thje Greaselion service to disallow incognito injection: https://github.com/brave/brave-core/commit/6bbdfb1137381be8787bdb39462c544446f8ce54. So I think we should be good on that front.

2021-03-22 21:55 UTC, diracdeltas commented
Yubico has agreed to work on this from their end: https://bravesoftware.slack.com/archives/CJMAD25L7/p1616449958005200?thread_ts=1616446792.001900&cid=CJMAD25L7. Can we close this out for now?

2021-03-29 15:06 UTC, amirsaber commented
Closing this in favor of better approach

2021-03-29 15:06 UTC, closed without merging